name: Check OIDC Token Claims

on: 
  push:
    branches:
      - main

jobs:
  check-token:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print OIDC Token Claims
        run: |
          # Decode the GitHub Actions OIDC token claims
          echo "${{ secrets.GITHUB_TOKEN }}" | awk -F. '{print $2}' | base64 --decode | jq .