name: Deploy GKE Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: HashiCorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Display Project ID (Debug)
        run: |
         echo "Project ID is: ${{ secrets.GCP_PROJECT_ID }}"
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # Set environment variable for direct check

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var project_id=${{ secrets.GCP_PROJECT_ID }}
        working-directory: terraform