name: Deploy to GCP

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to GCP
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/1021252187250/locations/global/workloadIdentityPools/github-actions'
          service_account: 'github-actions-sa@qdrant-445801.iam.gserviceaccount.com'

      - name: Configure GCP
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Run Terraform or any GCP commands
        run: |
          terraform init
          terraform apply -auto-approve